// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'core.freezed.dart';

/// Patch describing parameter updates to apply to the running engine.
class ParamPatch {
  final int? bpm;
  final double? centroidThreshold;
  final double? zcrThreshold;

  const ParamPatch({this.bpm, this.centroidThreshold, this.zcrThreshold});

  @override
  int get hashCode =>
      bpm.hashCode ^ centroidThreshold.hashCode ^ zcrThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParamPatch &&
          runtimeType == other.runtimeType &&
          bpm == other.bpm &&
          centroidThreshold == other.centroidThreshold &&
          zcrThreshold == other.zcrThreshold;
}

/// Telemetry event emitted by the engine core.
class TelemetryEvent {
  final BigInt timestampMs;
  final TelemetryEventKind kind;
  final String? detail;

  const TelemetryEvent({
    required this.timestampMs,
    required this.kind,
    this.detail,
  });

  @override
  int get hashCode => timestampMs.hashCode ^ kind.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelemetryEvent &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          kind == other.kind &&
          detail == other.detail;
}

@freezed
sealed class TelemetryEventKind with _$TelemetryEventKind {
  const TelemetryEventKind._();

  const factory TelemetryEventKind.engineStarted({required int bpm}) =
      TelemetryEventKind_EngineStarted;
  const factory TelemetryEventKind.engineStopped() =
      TelemetryEventKind_EngineStopped;
  const factory TelemetryEventKind.bpmChanged({required int bpm}) =
      TelemetryEventKind_BpmChanged;
  const factory TelemetryEventKind.warning() = TelemetryEventKind_Warning;
}
