// AUTO-GENERATED FILE - DO NOT EDIT
// This file will be generated by flutter_rust_bridge_codegen
//
// To generate this file, run:
//   flutter_rust_bridge_codegen generate
//
// STUB FILE: This is a temporary stub until codegen is run.
// The actual FFI glue code will be generated from rust/src/api.rs

// This file contains the low-level FFI bindings between Rust and Dart.
// It will be automatically generated when you run the codegen tool.
