// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1711875077;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__calibration_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calibration_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::calibration::progress::CalibrationProgress,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::calibration_stream(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__classification_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "classification_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::analysis::ClassificationResult,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::classification_stream(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__finish_calibration_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "finish_calibration",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::CalibrationError>((move || {
                    let output_ok = crate::api::finish_calibration()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_audio_error_codes_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_audio_error_codes",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::get_audio_error_codes())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_calibration_error_codes_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_calibration_error_codes",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::get_calibration_error_codes())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_calibration_state_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_calibration_state",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::CalibrationError>((move || {
                    let output_ok = crate::api::get_calibration_state()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::get_version()?;
                    Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::greet(api_name)?;
                    Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__load_calibration_state_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_calibration_state",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::CalibrationError>((move || {
                    let output_ok = crate::api::load_calibration_state(api_json)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__set_bpm_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_bpm",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bpm = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::AudioError>((move || {
                    let output_ok = crate::api::set_bpm(api_bpm)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__start_audio_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_audio",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bpm = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::AudioError>((move || {
                    let output_ok = crate::api::start_audio(api_bpm)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__start_calibration_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_calibration",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::CalibrationError>((move || {
                    let output_ok = crate::api::start_calibration()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__stop_audio_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_audio",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::error::AudioError>((move || {
                    let output_ok = crate::api::stop_audio()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::calibration::progress::CalibrationProgress,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::analysis::ClassificationResult,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::error::AudioError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_bpm = <u32>::sse_decode(deserializer);
                return crate::error::AudioError::BpmInvalid { bpm: var_bpm };
            }
            1 => {
                return crate::error::AudioError::AlreadyRunning;
            }
            2 => {
                return crate::error::AudioError::NotRunning;
            }
            3 => {
                let mut var_details = <String>::sse_decode(deserializer);
                return crate::error::AudioError::HardwareError {
                    details: var_details,
                };
            }
            4 => {
                return crate::error::AudioError::PermissionDenied;
            }
            5 => {
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::error::AudioError::StreamOpenFailed { reason: var_reason };
            }
            6 => {
                let mut var_component = <String>::sse_decode(deserializer);
                return crate::error::AudioError::LockPoisoned {
                    component: var_component,
                };
            }
            7 => {
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::error::AudioError::JniInitFailed { reason: var_reason };
            }
            8 => {
                return crate::error::AudioError::ContextNotInitialized;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::error::AudioErrorCodes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        return crate::error::AudioErrorCodes {};
    }
}

impl SseDecode for crate::analysis::classifier::BeatboxHit {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::analysis::classifier::BeatboxHit::Kick,
            1 => crate::analysis::classifier::BeatboxHit::Snare,
            2 => crate::analysis::classifier::BeatboxHit::HiHat,
            3 => crate::analysis::classifier::BeatboxHit::ClosedHiHat,
            4 => crate::analysis::classifier::BeatboxHit::OpenHiHat,
            5 => crate::analysis::classifier::BeatboxHit::KSnare,
            6 => crate::analysis::classifier::BeatboxHit::Unknown,
            _ => unreachable!("Invalid variant for BeatboxHit: {}", inner),
        };
    }
}

impl SseDecode for crate::error::CalibrationError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_required_ = <usize>::sse_decode(deserializer);
                let mut var_collected = <usize>::sse_decode(deserializer);
                return crate::error::CalibrationError::InsufficientSamples {
                    required: var_required_,
                    collected: var_collected,
                };
            }
            1 => {
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::error::CalibrationError::InvalidFeatures { reason: var_reason };
            }
            2 => {
                return crate::error::CalibrationError::NotComplete;
            }
            3 => {
                return crate::error::CalibrationError::AlreadyInProgress;
            }
            4 => {
                return crate::error::CalibrationError::StatePoisoned;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::error::CalibrationErrorCodes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        return crate::error::CalibrationErrorCodes {};
    }
}

impl SseDecode for crate::calibration::progress::CalibrationProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_currentSound =
            <crate::calibration::progress::CalibrationSound>::sse_decode(deserializer);
        let mut var_samplesCollected = <u8>::sse_decode(deserializer);
        let mut var_samplesNeeded = <u8>::sse_decode(deserializer);
        return crate::calibration::progress::CalibrationProgress {
            current_sound: var_currentSound,
            samples_collected: var_samplesCollected,
            samples_needed: var_samplesNeeded,
        };
    }
}

impl SseDecode for crate::calibration::progress::CalibrationSound {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::calibration::progress::CalibrationSound::Kick,
            1 => crate::calibration::progress::CalibrationSound::Snare,
            2 => crate::calibration::progress::CalibrationSound::HiHat,
            _ => unreachable!("Invalid variant for CalibrationSound: {}", inner),
        };
    }
}

impl SseDecode for crate::analysis::ClassificationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sound = <crate::analysis::classifier::BeatboxHit>::sse_decode(deserializer);
        let mut var_timing = <crate::analysis::quantizer::TimingFeedback>::sse_decode(deserializer);
        let mut var_timestampMs = <u64>::sse_decode(deserializer);
        let mut var_confidence = <f32>::sse_decode(deserializer);
        return crate::analysis::ClassificationResult {
            sound: var_sound,
            timing: var_timing,
            timestamp_ms: var_timestampMs,
            confidence: var_confidence,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::analysis::quantizer::TimingClassification {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::analysis::quantizer::TimingClassification::OnTime,
            1 => crate::analysis::quantizer::TimingClassification::Early,
            2 => crate::analysis::quantizer::TimingClassification::Late,
            _ => unreachable!("Invalid variant for TimingClassification: {}", inner),
        };
    }
}

impl SseDecode for crate::analysis::quantizer::TimingFeedback {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_classification =
            <crate::analysis::quantizer::TimingClassification>::sse_decode(deserializer);
        let mut var_errorMs = <f32>::sse_decode(deserializer);
        return crate::analysis::quantizer::TimingFeedback {
            classification: var_classification,
            error_ms: var_errorMs,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__calibration_stream_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__classification_stream_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__finish_calibration_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__get_calibration_state_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__init_app_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__load_calibration_state_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__set_bpm_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__start_audio_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__start_calibration_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__api__stop_audio_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        4 => wire__crate__api__get_audio_error_codes_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__get_calibration_error_codes_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__get_version_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__greet_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::error::AudioError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::error::AudioError::BpmInvalid { bpm } => {
                [0.into_dart(), bpm.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AudioError::AlreadyRunning => [1.into_dart()].into_dart(),
            crate::error::AudioError::NotRunning => [2.into_dart()].into_dart(),
            crate::error::AudioError::HardwareError { details } => {
                [3.into_dart(), details.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AudioError::PermissionDenied => [4.into_dart()].into_dart(),
            crate::error::AudioError::StreamOpenFailed { reason } => {
                [5.into_dart(), reason.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AudioError::LockPoisoned { component } => {
                [6.into_dart(), component.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AudioError::JniInitFailed { reason } => {
                [7.into_dart(), reason.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AudioError::ContextNotInitialized => [8.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::error::AudioError {}
impl flutter_rust_bridge::IntoIntoDart<crate::error::AudioError> for crate::error::AudioError {
    fn into_into_dart(self) -> crate::error::AudioError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::error::AudioErrorCodes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        Vec::<u8>::new().into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::error::AudioErrorCodes {}
impl flutter_rust_bridge::IntoIntoDart<crate::error::AudioErrorCodes>
    for crate::error::AudioErrorCodes
{
    fn into_into_dart(self) -> crate::error::AudioErrorCodes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::analysis::classifier::BeatboxHit {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Kick => 0.into_dart(),
            Self::Snare => 1.into_dart(),
            Self::HiHat => 2.into_dart(),
            Self::ClosedHiHat => 3.into_dart(),
            Self::OpenHiHat => 4.into_dart(),
            Self::KSnare => 5.into_dart(),
            Self::Unknown => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::analysis::classifier::BeatboxHit
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::analysis::classifier::BeatboxHit>
    for crate::analysis::classifier::BeatboxHit
{
    fn into_into_dart(self) -> crate::analysis::classifier::BeatboxHit {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::error::CalibrationError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::error::CalibrationError::InsufficientSamples {
                required,
                collected,
            } => [
                0.into_dart(),
                required.into_into_dart().into_dart(),
                collected.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::error::CalibrationError::InvalidFeatures { reason } => {
                [1.into_dart(), reason.into_into_dart().into_dart()].into_dart()
            }
            crate::error::CalibrationError::NotComplete => [2.into_dart()].into_dart(),
            crate::error::CalibrationError::AlreadyInProgress => [3.into_dart()].into_dart(),
            crate::error::CalibrationError::StatePoisoned => [4.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::error::CalibrationError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::error::CalibrationError>
    for crate::error::CalibrationError
{
    fn into_into_dart(self) -> crate::error::CalibrationError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::error::CalibrationErrorCodes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        Vec::<u8>::new().into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::error::CalibrationErrorCodes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::error::CalibrationErrorCodes>
    for crate::error::CalibrationErrorCodes
{
    fn into_into_dart(self) -> crate::error::CalibrationErrorCodes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::calibration::progress::CalibrationProgress {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.current_sound.into_into_dart().into_dart(),
            self.samples_collected.into_into_dart().into_dart(),
            self.samples_needed.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::calibration::progress::CalibrationProgress
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::calibration::progress::CalibrationProgress>
    for crate::calibration::progress::CalibrationProgress
{
    fn into_into_dart(self) -> crate::calibration::progress::CalibrationProgress {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::calibration::progress::CalibrationSound {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Kick => 0.into_dart(),
            Self::Snare => 1.into_dart(),
            Self::HiHat => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::calibration::progress::CalibrationSound
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::calibration::progress::CalibrationSound>
    for crate::calibration::progress::CalibrationSound
{
    fn into_into_dart(self) -> crate::calibration::progress::CalibrationSound {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::analysis::ClassificationResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sound.into_into_dart().into_dart(),
            self.timing.into_into_dart().into_dart(),
            self.timestamp_ms.into_into_dart().into_dart(),
            self.confidence.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::analysis::ClassificationResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::analysis::ClassificationResult>
    for crate::analysis::ClassificationResult
{
    fn into_into_dart(self) -> crate::analysis::ClassificationResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::analysis::quantizer::TimingClassification {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::OnTime => 0.into_dart(),
            Self::Early => 1.into_dart(),
            Self::Late => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::analysis::quantizer::TimingClassification
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::analysis::quantizer::TimingClassification>
    for crate::analysis::quantizer::TimingClassification
{
    fn into_into_dart(self) -> crate::analysis::quantizer::TimingClassification {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::analysis::quantizer::TimingFeedback {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.classification.into_into_dart().into_dart(),
            self.error_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::analysis::quantizer::TimingFeedback
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::analysis::quantizer::TimingFeedback>
    for crate::analysis::quantizer::TimingFeedback
{
    fn into_into_dart(self) -> crate::analysis::quantizer::TimingFeedback {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::calibration::progress::CalibrationProgress,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::analysis::ClassificationResult,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::error::AudioError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::error::AudioError::BpmInvalid { bpm } => {
                <i32>::sse_encode(0, serializer);
                <u32>::sse_encode(bpm, serializer);
            }
            crate::error::AudioError::AlreadyRunning => {
                <i32>::sse_encode(1, serializer);
            }
            crate::error::AudioError::NotRunning => {
                <i32>::sse_encode(2, serializer);
            }
            crate::error::AudioError::HardwareError { details } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(details, serializer);
            }
            crate::error::AudioError::PermissionDenied => {
                <i32>::sse_encode(4, serializer);
            }
            crate::error::AudioError::StreamOpenFailed { reason } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::error::AudioError::LockPoisoned { component } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(component, serializer);
            }
            crate::error::AudioError::JniInitFailed { reason } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::error::AudioError::ContextNotInitialized => {
                <i32>::sse_encode(8, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::error::AudioErrorCodes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::analysis::classifier::BeatboxHit {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::analysis::classifier::BeatboxHit::Kick => 0,
                crate::analysis::classifier::BeatboxHit::Snare => 1,
                crate::analysis::classifier::BeatboxHit::HiHat => 2,
                crate::analysis::classifier::BeatboxHit::ClosedHiHat => 3,
                crate::analysis::classifier::BeatboxHit::OpenHiHat => 4,
                crate::analysis::classifier::BeatboxHit::KSnare => 5,
                crate::analysis::classifier::BeatboxHit::Unknown => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::error::CalibrationError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::error::CalibrationError::InsufficientSamples {
                required,
                collected,
            } => {
                <i32>::sse_encode(0, serializer);
                <usize>::sse_encode(required, serializer);
                <usize>::sse_encode(collected, serializer);
            }
            crate::error::CalibrationError::InvalidFeatures { reason } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::error::CalibrationError::NotComplete => {
                <i32>::sse_encode(2, serializer);
            }
            crate::error::CalibrationError::AlreadyInProgress => {
                <i32>::sse_encode(3, serializer);
            }
            crate::error::CalibrationError::StatePoisoned => {
                <i32>::sse_encode(4, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::error::CalibrationErrorCodes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::calibration::progress::CalibrationProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::calibration::progress::CalibrationSound>::sse_encode(
            self.current_sound,
            serializer,
        );
        <u8>::sse_encode(self.samples_collected, serializer);
        <u8>::sse_encode(self.samples_needed, serializer);
    }
}

impl SseEncode for crate::calibration::progress::CalibrationSound {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::calibration::progress::CalibrationSound::Kick => 0,
                crate::calibration::progress::CalibrationSound::Snare => 1,
                crate::calibration::progress::CalibrationSound::HiHat => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::analysis::ClassificationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::analysis::classifier::BeatboxHit>::sse_encode(self.sound, serializer);
        <crate::analysis::quantizer::TimingFeedback>::sse_encode(self.timing, serializer);
        <u64>::sse_encode(self.timestamp_ms, serializer);
        <f32>::sse_encode(self.confidence, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::analysis::quantizer::TimingClassification {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::analysis::quantizer::TimingClassification::OnTime => 0,
                crate::analysis::quantizer::TimingClassification::Early => 1,
                crate::analysis::quantizer::TimingClassification::Late => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::analysis::quantizer::TimingFeedback {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::analysis::quantizer::TimingClassification>::sse_encode(
            self.classification,
            serializer,
        );
        <f32>::sse_encode(self.error_ms, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
