// AUTO-GENERATED FILE - DO NOT EDIT
// This file will be generated by flutter_rust_bridge_codegen
//
// To generate this file, run:
//   flutter_rust_bridge_codegen generate
//
// STUB FILE: This is a temporary stub until codegen is run.
// The actual implementation will be generated from rust/src/api.rs

import '../models/classification_result.dart';

/// Stub API functions - will be replaced by codegen

/// Start audio engine with specified BPM
Future<void> startAudio({required int bpm}) async {
  throw UnimplementedError(
    'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
  );
}

/// Stop audio engine
Future<void> stopAudio() async {
  throw UnimplementedError(
    'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
  );
}

/// Set BPM dynamically during audio playback
Future<void> setBpm({required int bpm}) async {
  throw UnimplementedError(
    'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
  );
}

/// Stream of classification results
Stream<ClassificationResult> classificationStream() {
  throw UnimplementedError(
    'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
  );
}

/// Start calibration workflow
Future<void> startCalibration() async {
  throw UnimplementedError(
    'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
  );
}

/// Finish calibration and compute thresholds
Future<void> finishCalibration() async {
  throw UnimplementedError(
    'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
  );
}
