// AUTO-GENERATED FILE - DO NOT EDIT
// This file will be generated by flutter_rust_bridge_codegen
//
// To generate this file, run:
//   flutter_rust_bridge_codegen generate
//
// STUB FILE: This is a temporary stub until codegen is run.
// The actual implementation will be generated from rust/src/api.rs

/// Stub API class - will be replaced by codegen
class BeatboxTrainerApi {
  /// Greet function stub
  Future<String> greet({required String name}) async {
    throw UnimplementedError(
      'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
    );
  }

  /// Get version stub
  Future<String> getVersion() async {
    throw UnimplementedError(
      'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
    );
  }

  /// Add numbers stub
  Future<int> addNumbers({required int a, required int b}) async {
    throw UnimplementedError(
      'This is a stub. Run flutter_rust_bridge_codegen generate to create the actual implementation.',
    );
  }
}
