// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Progress information for the current calibration step
///
/// This struct is sent to the Dart UI via flutter_rust_bridge Stream
/// for real-time display of calibration progress.
class CalibrationProgress {
  /// Current sound being calibrated
  final CalibrationSound currentSound;

  /// Number of samples collected for current sound (0-10)
  final int samplesCollected;

  /// Total samples needed per sound
  final int samplesNeeded;

  const CalibrationProgress({
    required this.currentSound,
    required this.samplesCollected,
    required this.samplesNeeded,
  });

  @override
  int get hashCode =>
      currentSound.hashCode ^
      samplesCollected.hashCode ^
      samplesNeeded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalibrationProgress &&
          runtimeType == other.runtimeType &&
          currentSound == other.currentSound &&
          samplesCollected == other.samplesCollected &&
          samplesNeeded == other.samplesNeeded;
}

/// Sound type being calibrated
enum CalibrationSound { kick, snare, hiHat }
