// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Progress information for the current calibration step
///
/// This struct is sent to the Dart UI via flutter_rust_bridge Stream
/// for real-time display of calibration progress.
class CalibrationProgress {
  /// Current sound being calibrated
  final CalibrationSound currentSound;

  /// Number of samples collected for current sound (0-10)
  final int samplesCollected;

  /// Total samples needed per sound
  final int samplesNeeded;

  /// Whether waiting for user confirmation to proceed to next phase
  final bool waitingForConfirmation;

  const CalibrationProgress({
    required this.currentSound,
    required this.samplesCollected,
    required this.samplesNeeded,
    required this.waitingForConfirmation,
  });

  @override
  int get hashCode =>
      currentSound.hashCode ^
      samplesCollected.hashCode ^
      samplesNeeded.hashCode ^
      waitingForConfirmation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalibrationProgress &&
          runtimeType == other.runtimeType &&
          currentSound == other.currentSound &&
          samplesCollected == other.samplesCollected &&
          samplesNeeded == other.samplesNeeded &&
          waitingForConfirmation == other.waitingForConfirmation;
}

/// Calibration phase - includes noise floor measurement before sound collection
enum CalibrationSound {
  /// Step 1: Measuring ambient noise level (user should stay quiet)
  noiseFloor,

  /// Step 2: Collecting kick drum samples
  kick,

  /// Step 3: Collecting snare drum samples
  snare,

  /// Step 4: Collecting hi-hat samples
  hiHat,
}
