// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// CalibrationState stores thresholds for sound classification
class CalibrationState {
  /// Classifier level (1 = beginner with 3 categories, 2 = advanced with 6 categories)
  /// Defaults to 1 for backward compatibility
  final int level;

  /// Threshold for kick drum centroid (Hz)
  final double tKickCentroid;

  /// Threshold for kick drum ZCR
  final double tKickZcr;

  /// Threshold for snare drum centroid (Hz)
  final double tSnareCentroid;

  /// Threshold for hi-hat ZCR
  final double tHihatZcr;

  /// Whether the system has been calibrated
  final bool isCalibrated;

  /// Noise floor RMS threshold for onset gating in training mode
  /// Defaults to 0.01 for backward compatibility with existing calibrations
  final double noiseFloorRms;

  const CalibrationState({
    required this.level,
    required this.tKickCentroid,
    required this.tKickZcr,
    required this.tSnareCentroid,
    required this.tHihatZcr,
    required this.isCalibrated,
    required this.noiseFloorRms,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      tKickCentroid.hashCode ^
      tKickZcr.hashCode ^
      tSnareCentroid.hashCode ^
      tHihatZcr.hashCode ^
      isCalibrated.hashCode ^
      noiseFloorRms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalibrationState &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          tKickCentroid == other.tKickCentroid &&
          tKickZcr == other.tKickZcr &&
          tSnareCentroid == other.tSnareCentroid &&
          tHihatZcr == other.tHihatZcr &&
          isCalibrated == other.isCalibrated &&
          noiseFloorRms == other.noiseFloorRms;
}
