// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'analysis/classifier.dart';
import 'analysis/quantizer.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Classification result combining sound type and timing feedback
///
/// This struct is sent to the Dart UI via flutter_rust_bridge Stream
/// for real-time display of detected sounds and timing accuracy.
class ClassificationResult {
  /// Detected beatbox sound type
  final BeatboxHit sound;

  /// Timing accuracy relative to metronome grid
  final TimingFeedback timing;

  /// Timestamp in milliseconds since engine start
  final BigInt timestampMs;

  /// Classification confidence score (0.0-1.0)
  final double confidence;

  const ClassificationResult({
    required this.sound,
    required this.timing,
    required this.timestampMs,
    required this.confidence,
  });

  @override
  int get hashCode => sound.hashCode ^ timing.hashCode ^ timestampMs.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassificationResult &&
          runtimeType == other.runtimeType &&
          sound == other.sound &&
          timing == other.timing &&
          timestampMs == other.timestampMs &&
          confidence == other.confidence;
}
