// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class AudioError with _$AudioError implements FrbException {
  const AudioError._();

  /// BPM value is invalid (must be > 0, typically 40-240)
  const factory AudioError.bpmInvalid({required int bpm}) =
      AudioError_BpmInvalid;

  /// Audio engine is already running
  const factory AudioError.alreadyRunning() = AudioError_AlreadyRunning;

  /// Audio engine is not running
  const factory AudioError.notRunning() = AudioError_NotRunning;

  /// Hardware error occurred
  const factory AudioError.hardwareError({required String details}) =
      AudioError_HardwareError;

  /// Microphone permission denied
  const factory AudioError.permissionDenied() = AudioError_PermissionDenied;

  /// Failed to open audio stream
  const factory AudioError.streamOpenFailed({required String reason}) =
      AudioError_StreamOpenFailed;

  /// Mutex/RwLock was poisoned
  const factory AudioError.lockPoisoned({required String component}) =
      AudioError_LockPoisoned;

  /// JNI initialization failed on Android
  const factory AudioError.jniInitFailed({required String reason}) =
      AudioError_JniInitFailed;

  /// Android context was not initialized before audio engine start
  const factory AudioError.contextNotInitialized() =
      AudioError_ContextNotInitialized;
}

@freezed
sealed class CalibrationError with _$CalibrationError implements FrbException {
  const CalibrationError._();

  /// Insufficient samples collected for calibration
  const factory CalibrationError.insufficientSamples({
    required BigInt required_,
    required BigInt collected,
  }) = CalibrationError_InsufficientSamples;

  /// Invalid features extracted from samples
  const factory CalibrationError.invalidFeatures({required String reason}) =
      CalibrationError_InvalidFeatures;

  /// Calibration not complete
  const factory CalibrationError.notComplete() = CalibrationError_NotComplete;

  /// Calibration already in progress
  const factory CalibrationError.alreadyInProgress() =
      CalibrationError_AlreadyInProgress;

  /// Calibration state RwLock was poisoned
  const factory CalibrationError.statePoisoned() =
      CalibrationError_StatePoisoned;
}
