// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import '../testing/fixtures.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            /// Start a diagnostics fixture session feeding PCM data into the DSP pipeline.
Future<void>  startFixtureSession({required FixtureSpec spec }) => RustLib.instance.api.crateApiDiagnosticsStartFixtureSession(spec: spec);

/// Stop the currently running diagnostics fixture session, if any.
void  stopFixtureSession() => RustLib.instance.api.crateApiDiagnosticsStopFixtureSession();

            
            