// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../analysis.dart';
import '../analysis/classifier.dart';
import '../analysis/quantizer.dart';
import '../engine/core.dart';
import '../frb_generated.dart';
import '../telemetry/events.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Stream of audio metrics for debug visualization
///
/// Emits AudioMetrics with real-time DSP metrics from the audio processing pipeline.
/// Useful for debugging and development.
Stream<AudioMetrics> audioMetricsStream() =>
    RustLib.instance.api.crateApiStreamsAudioMetricsStream();

/// Stream of telemetry events for debug instrumentation
///
/// Emits engine lifecycle events (start/stop, BPM changes) and warnings.
Stream<TelemetryEvent> telemetryStream() =>
    RustLib.instance.api.crateApiStreamsTelemetryStream();

/// Stream of diagnostic metrics aggregated from telemetry hub.
Stream<MetricEvent> diagnosticMetricsStream() =>
    RustLib.instance.api.crateApiStreamsDiagnosticMetricsStream();

/// Stream of onset events for debug visualization
///
/// Emits OnsetEvent whenever an onset is detected.
Stream<OnsetEvent> onsetEventsStream() =>
    RustLib.instance.api.crateApiStreamsOnsetEventsStream();
