// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../analysis/classifier.dart';
import '../engine/core.dart';
import '../frb_generated.dart';
import '../telemetry/events.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `audio_metrics_stream`, `onset_events_stream`

/// Stream of telemetry events for debug instrumentation
///
/// Emits engine lifecycle events (start/stop, BPM changes) and warnings.
Stream<TelemetryEvent> telemetryStream() =>
    RustLib.instance.api.crateApiStreamsTelemetryStream();

/// Stream of diagnostic metrics aggregated from telemetry hub.
Stream<MetricEvent> diagnosticMetricsStream() =>
    RustLib.instance.api.crateApiStreamsDiagnosticMetricsStream();
