// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../analysis.dart';
import '../analysis/classifier.dart';
import '../analysis/quantizer.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Audio metrics for debug visualization
class AudioMetrics {
  final double rms;
  final double spectralCentroid;
  final double spectralFlux;
  final BigInt frameNumber;
  final BigInt timestamp;

  const AudioMetrics({
    required this.rms,
    required this.spectralCentroid,
    required this.spectralFlux,
    required this.frameNumber,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      rms.hashCode ^
      spectralCentroid.hashCode ^
      spectralFlux.hashCode ^
      frameNumber.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioMetrics &&
          runtimeType == other.runtimeType &&
          rms == other.rms &&
          spectralCentroid == other.spectralCentroid &&
          spectralFlux == other.spectralFlux &&
          frameNumber == other.frameNumber &&
          timestamp == other.timestamp;
}

/// Keys for updating calibration thresholds
enum CalibrationThresholdKey {
  kickCentroid,
  kickZcr,
  snareCentroid,
  hihatZcr,
  noiseFloorRms,
}

/// Onset event with classification details
class OnsetEvent {
  final BigInt timestamp;
  final double energy;
  final double centroid;
  final double zcr;
  final double flatness;
  final double rolloff;
  final double decayTimeMs;
  final ClassificationResult? classification;

  const OnsetEvent({
    required this.timestamp,
    required this.energy,
    required this.centroid,
    required this.zcr,
    required this.flatness,
    required this.rolloff,
    required this.decayTimeMs,
    this.classification,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      energy.hashCode ^
      centroid.hashCode ^
      zcr.hashCode ^
      flatness.hashCode ^
      rolloff.hashCode ^
      decayTimeMs.hashCode ^
      classification.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnsetEvent &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          energy == other.energy &&
          centroid == other.centroid &&
          zcr == other.zcr &&
          flatness == other.flatness &&
          rolloff == other.rolloff &&
          decayTimeMs == other.decayTimeMs &&
          classification == other.classification;
}
