// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// BeatboxHit represents classified beatbox sounds
///
/// Level 1 sounds: Kick, Snare, HiHat
/// Level 2 adds subcategories: ClosedHiHat, OpenHiHat, KSnare
enum BeatboxHit {
  /// Kick drum (low frequency, low ZCR)
  kick,

  /// Snare drum (mid frequency)
  snare,

  /// Hi-hat (high frequency, high ZCR) - Level 1 generic
  hiHat,

  /// Closed hi-hat (short decay) - Level 2
  closedHiHat,

  /// Open hi-hat (long decay) - Level 2
  openHiHat,

  /// K-snare (kick+snare hybrid, noisy kick) - Level 2
  kSnare,

  /// Unknown sound (doesn't match any pattern)
  unknown,
}
