// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Timing classification for onset accuracy relative to metronome grid
///
/// Determines whether a detected onset is on-time, early, or late relative
/// to the nearest beat boundary.
enum TimingClassification {
  /// Onset is within 50ms of a beat boundary
  onTime,

  /// Onset is too early (more than 50ms before nearest beat, but closer to previous beat)
  early,

  /// Onset is too late (more than 50ms after beat boundary)
  late_,
}

/// Timing feedback with classification and millisecond error
///
/// Provides detailed timing feedback for display to the user, including
/// the classification (ON_TIME/EARLY/LATE) and the signed error in milliseconds.
class TimingFeedback {
  /// Classification of timing accuracy
  final TimingClassification classification;

  /// Timing error in milliseconds
  /// - Positive values indicate late (after beat)
  /// - Negative values indicate early (before beat)
  /// - Zero indicates exactly on beat
  final double errorMs;

  const TimingFeedback({required this.classification, required this.errorMs});

  @override
  int get hashCode => classification.hashCode ^ errorMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimingFeedback &&
          runtimeType == other.runtimeType &&
          classification == other.classification &&
          errorMs == other.errorMs;
}
