// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'audio.freezed.dart';

@freezed
sealed class AudioError with _$AudioError implements FrbException {
  const AudioError._();

  /// BPM value is invalid (must be > 0, typically 40-240)
  const factory AudioError.bpmInvalid({required int bpm}) =
      AudioError_BpmInvalid;

  /// Audio engine is already running
  const factory AudioError.alreadyRunning() = AudioError_AlreadyRunning;

  /// Audio engine is not running
  const factory AudioError.notRunning() = AudioError_NotRunning;

  /// Hardware error occurred
  const factory AudioError.hardwareError({required String details}) =
      AudioError_HardwareError;

  /// Microphone permission denied
  const factory AudioError.permissionDenied() = AudioError_PermissionDenied;

  /// Failed to open audio stream
  const factory AudioError.streamOpenFailed({required String reason}) =
      AudioError_StreamOpenFailed;

  /// Mutex/RwLock was poisoned
  const factory AudioError.lockPoisoned({required String component}) =
      AudioError_LockPoisoned;

  /// JNI initialization failed on Android
  const factory AudioError.jniInitFailed({required String reason}) =
      AudioError_JniInitFailed;

  /// Android context was not initialized before audio engine start
  const factory AudioError.contextNotInitialized() =
      AudioError_ContextNotInitialized;

  /// Stream channel disconnected unexpectedly
  const factory AudioError.streamFailure({required String reason}) =
      AudioError_StreamFailure;
}

/// Audio error code constants exposed to Dart via FFI
///
/// These constants provide a single source of truth for error codes
/// shared between Rust and Dart. The flutter_rust_bridge will automatically
/// generate corresponding Dart constants.
///
/// Error code range: 1001-1010
class AudioErrorCodes {
  const AudioErrorCodes();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioErrorCodes && runtimeType == other.runtimeType;
}
