// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'calibration.freezed.dart';

@freezed
sealed class CalibrationError with _$CalibrationError implements FrbException {
  const CalibrationError._();

  /// Insufficient samples collected for calibration
  const factory CalibrationError.insufficientSamples({
    required BigInt required_,
    required BigInt collected,
  }) = CalibrationError_InsufficientSamples;

  /// Invalid features extracted from samples
  const factory CalibrationError.invalidFeatures({required String reason}) =
      CalibrationError_InvalidFeatures;

  /// Calibration not complete
  const factory CalibrationError.notComplete() = CalibrationError_NotComplete;

  /// Calibration already in progress
  const factory CalibrationError.alreadyInProgress() =
      CalibrationError_AlreadyInProgress;

  /// Calibration state RwLock was poisoned
  const factory CalibrationError.statePoisoned() =
      CalibrationError_StatePoisoned;

  /// Calibration timed out waiting for native engine coordination
  const factory CalibrationError.timeout({required String reason}) =
      CalibrationError_Timeout;
}

/// Calibration error code constants exposed to Dart via FFI
///
/// These constants provide a single source of truth for error codes
/// shared between Rust and Dart. The flutter_rust_bridge will automatically
/// generate corresponding Dart constants.
///
/// Error code range: 2001-2006
class CalibrationErrorCodes {
  const CalibrationErrorCodes();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalibrationErrorCodes && runtimeType == other.runtimeType;
}
